[Rainmeter]
Update=1000

[MeasureTime]
Measure=Time
; Hotra en formato de 24 horas (%H)
; Format=%H:%M:%S 
; Hora en formato de 12 horas (%I)
Format=%I:%M:%S
; Hora en formato de 12 horas (%I) con AM/PM (%p)
; Format=%I:%M:%S %p
; Dia en texto (%A)  Hora en formato de 12 horas (%I)
; Format=%A, %I:%M:%S

[MeasureDate]
Measure=Time
; Dia en texto (%A)  Fecha en formato de día/mes/año (%d/%m/%Y)
; Format=%A, %d/%m/%Y
; Dia en texto (%A)  Fecha en formato de día/mes texto/año (%d/%B/%Y)
Format=%A, %d/%B/%Y

; Se Actualiza la fecha cada minuto.
UpdateDivider=60
; Se multiplica 1000 * 60 = 60000 milisegundos, que es igual a 1 minuto.
; Poner UpdateDivider = 0, significa que se actualiza SIEMPRE...

[MeterTime]
Meter=String
MeasureName=MeasureTime
FontFace=Thomas
FontSize=20
FontColor=255,255,255
Text=Hora: %1
; %1 muestra el valor de la medida "MeasureTime"
Y=35

[MeterDate]
Meter=String
MeasureName=MeasureDate
FontFace=Thomas
FontSize=20
FontColor=255,255,255

[MeasureCPU]
Measure=CPU

[CPU]
Meter=String
MeasureName=MeasureCPU
Y=70

FontFace=#Fuente#
FontSize=18
FontColor=#Color#
Text=CPU: %1%

; Usar 2 measures en el mismo meter
[MeterInfo]
Meter=String
MeasureName=MeasureTime
MeasureName2=MeasureDate
FontFace=Thomas
FontSize=20
FontColor=255,255,255
Text=Hora: %1 | Fecha: %2
Y=125