[Rainmeter]
Update=1000

[Fondo]
Meter=Shape
Shape=Rectangle 0,0,300,120,10 | Fill Color 40,40,40,180 | StrokeWidth 5 | Stroke Color 0,0,0,255
X=0
Y=0

; Shape=Rectangle 0,0,300,120,10
; X , Y , Width , Height , CornerRadius

; Fill Color 40,40,40,180
; R , G , B , Alpha

[Fondo2]
Meter=Shape
Shape=Rectangle 0,0,300,120,10 | Fill Color 40,40,40,180
X=0
Y=130

[Fondo3]
Meter=Shape
Shape=Rectangle 0,0,300,120,10 | Fill Color 40,40,40,180 | StrokeWidth 0
X=0
Y=260