[Rainmeter]
Update=1000

[Variables]
; VWidth=1920
VWidth=300
VHeight=120
VCornerRadius=10
Vshape=Rectangle 0,0,#VWidth#,#VHeight#,#VCornerRadius#
VFface=Thomas
VFsize=20
VFcolor=255,255,255

[rectangle]
Meter=Shape
Shape=#Vshape# | Fill Color 40,40,40,180 | StrokeWidth 0

[Title]
Meter=String
Text=Stranger 11
FontFace=#VFface#
FontSize=#VFsize#
FontColor=#VFcolor#
X=((#VWidth#/2) - (#VFsize#*3.5))
Y=((#VHeight#/2) - #VFsize#)